module ErrorOps {

    public transactional fun Throw():() {
        abort;
    };

    public fun CatchOne():(r:Bool.Bool) {
        return try call .Throw(){
           success => {
               return pack Bool.Bool#False();
           };
           failure => {
               return pack Bool.Bool#True();
           };
        };
    };

    public transactional fun Propagate():() {
        return call .Throw();
    };


    public fun CatchPropagate():(r:Bool.Bool) {
        return try call .Propagate(){
           success => {
               return pack Bool.Bool#False();
           };
           failure => {
               return pack Bool.Bool#True();
           };
       };
    };

    public transactional fun NoThrow():() {
        return;
    };
}