module TestFailBranchReturnType4 {
    err X;

    private fun Test[<Drop> A, <Drop> B](consume a:A, consume b:B):(a3:A){
        a3 = try {
            a2 = a;
            b2 = b;
            return a2;
        } catch {
            .X => {
                a2 = a;
                b2 = b;
                return b2;
            };
        };

        return a3;
    };
}