module TestFailBranchReturnType5 {
    err X;

    private fun Test[<Drop, Copy> A](a:A, b:A):(a3:A, b3:A){
        (a3,b3,c3) = try {
            a2 = copy a;
            b2 = copy b;
            c2 = &a2;
            return (a2,b2,c2);
        } catch {
            .X => {
                a2 = copy a;
                b2 = copy b;
                c2 = &b2;
                return (a2,b2,c2);
            };
        };

        return (a3, b3);
    };
}