module TestFailThrow2 {
    err X;
    err Y;

    risky <.Y> fun Test():(){
        throw .X;
    };
}