module TestFailThrow3 {
    err X;
    err Y;

    fun Test():(){
        () = try {
            throw .X;
        } catch {
           .Y => {
              return;
           };
        };
        return;
    };
}